<style>
	note {
		LineColor #b5e1b3
        LineThickness 1
        BackgroundColor #ffffff
	}
</style>
skinparam {
	Arrow {
    	Color #fc71ff
        Thickness 1
    }
    
    Participant {
    	BorderColor #91c3fd
      	BorderThickness 1
    	BackgroundColor #ffffff
    }
    
    Sequence {
    	Group {
        	BorderColor #fdb471
            BorderThickness 1
            BackgroundColor #fedfc1
        }
    }
}
